language: go

go:
  - "1.13.x"
  - "1.14.x"
  - stable
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - $HOME/gopath/bin/goveralls -repotoken 0xSFQUzYPLhYSnrTQLtdL7sWCWEnt9dG8 || true
  - go test -v -test.bench=".*" -test.benchmem=true .